In [ ]:
import requests
import numpy as np
import pandas as pd
from bs4 import BeautifulSoup
field=[]
name=[]
location=[]
salary=[]
experience=[]

for j in range(1,50):
  print(j)
  headers = {
      'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.162 Safari/537.36'
  }

  url = 'https://internshala.com/jobs/page-{}'.format(j)
  webpage = requests.get(url, headers=headers).text
  soup= BeautifulSoup(webpage,'lxml')
  company= soup.find_all('div', class_='internship_meta')



  for i in company:
    name.append(i.find('p', class_='company-name').text.strip())
    try:
      field.append(i.find('a', class_= 'job-title-href').text.strip())
    except:
      field.append(np.nan)


    try:
      location.append(i.find('p',class_='location').text.strip())
    except:
      location.append(np.nan)

    try:
      salary.append(i.find_all( 'div',class_='row-1-item')[0].text.strip())
    except:
      salary.append(np.nan)

    try:
      experience.append(i.find_all('div',class_='row-1-item')[1] .text.strip())
    except:
      experience.append(np.nan)



    df=pd.DataFrame({'Sector':field,'Company Name':name,'Location':location,'Salary':salary,'Experience':experience})

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49

In [ ]:
df

,Sector,Company Name,Location,Salary,Experience
0,Corporate Sales Executive,Foodsure,NaN,"₹ 2,00,000 - 2,75,000 ...",1 year(s)
1,Shopify Expert,Stag International,NaN,"₹ 3,00,000 - 3,20,000 ...",1 year(s)
2,Operations Executive,Tarana Entertainments,NaN,"₹ 2,00,000 - 6,00,000 ...",1 year(s)
3,Business Development Executive,Fuel It Online,NaN,"₹ 2,00,000 - 7,50,000 ...",0 year(s)
4,Associate Accountant,PRASUN.Energy,NaN,"₹ 3,00,000 - 3,60,000 ...",1 year(s)
...,...,...,...,...,...
1965,Business Development Representative,Hire Xpert,NaN,"₹ 3,36,000 - 4,20,000 ...",2 year(s)
1966,Business Development Specialist,Truelancer,NaN,"₹ 3,36,000 - 3,96,000 ...",0 year(s)
1967,Business Development Executive,Truelancer,NaN,"₹ 3,36,000 - 3,96,000 ...",0 year(s)
1968,Business Development Associate,Truelancer,NaN,"₹ 3,36,000 - 3,96,000 ...",0 year(s)
1969,Business Development Associate,Truelancer,NaN,"₹ 3,36,000 - 3,96,000 ...",0 year(s)